### ISSUE TITLE
Try out your test

### ISSUE THREAD

**Issue by ohenley** [pyjarrett/progress_indicators#4]
Hi @pyjarrett ! 

Note: Sorry if this, maybe, is an Alire question but...

1. How would I build your test executable? ATM, I fail to build it both using Alire and plain gprbuild (because ansiada). I could make it 'by hand' but ...

As a first assessment of potential 'interest' for progress_indicators, it might be a good idea to expose the tests executable, so we, strangers, do not have to unroll our own use of libProgress_indicator 'just to see'.

Thank you,

ohenley

edit: Just swapped full name resolution for ansi.gpr inside progress_indicators.gpr to test out your progress_indicators_test.

I really like your test executable, showing me the capabilities real quick! Thx.

**Comment by pyjarrett** [comment]
The test executable is not exposed because [I've been told not to do so](https://github.com/alire-project/alire-index/pull/290) when submitting to Alire.  Septum [also uses the spinner](https://github.com/pyjarrett/septum/blob/68ac5fbcf36d05ebd6799d5807c407240284b4d6/src/sp-cache.adb#L186) if you're looking for a use case.

You should thank @onox, that's the genius behind the test executable.

**Comment by onox** [comment]
@pyjarrett I think the tests/ folder should have an alire.toml file. I'll add one and open a PR.
